- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete old Application Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /app
    remote_src: yes

- name: Copy package.json to /app
  copy:
    src: path/to/local/package.json
    dest: /app/package.json

